version: "3.0" # specify docker-compose version

# Define the services/ containers to be run
services:
  client: # name of the first service
    container_name: issue-app_client
    build: ./client # specify the directory of the Dockerfile
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./client/src:/home/node/app/src
    ports:
      - "4200:4200" # specify port mapping
    depends_on:
      - server

  server: # name of the second service
    container_name: issue-app_server
    build: ./server # specify the directory of the Dockerfile
    command: npm start
    ports:
      - "7000:7000" #specify ports mapping
    links:
      - database # link this service to the database service
    depends_on:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    container_name: issue-app_mongo
    command: mongod --noauth
    volumes:
      - ./database/db:/data/db
    ports:
      - "27017:27017" # specify port forwarding
